version: "2"
services:
    swarm_master:
        image: swarm
        restart: always
        ports:
           - 192.168.255.6:4000:4000
        network_mode: "host"
        command: manage -H :4000 --advertise 192.168.255.6:4000 consul://$CONSUL_HOST

    swarm_client :
        image: swarm
        depends_on:
            - "swarm_master"
        restart: always
        command: join --advertise 192.168.255.6:2375 consul://$CONSUL_HOST

    registry:
        image: registry:2
        restart: always
        ports:
            - 192.168.255.6:5000:5000
