consul:
    build: ./consul_ui
    ports:
        - 8300:8300
        - 8400:8400 
        - 10.0.0.8:8500:8500
        - 8600:53/udp
    command: agent -server -bootstrap -client 0.0.0.0 -data-dir /data -ui-dir /ui
    restart: always

swarm_master:
    image: swarm
    restart: always
    ports:
       - 10.0.0.8:4000:4000
    command: manage -H :4000 --advertise 10.0.0.8:4000 consul://10.0.0.8:8500

swarm_client :
    image: swarm
    restart: always
    command: join --advertise 10.0.0.8:2375 consul://10.0.0.8:8500

docker_ui:
    image: dockerui/dockerui
    restart: always
    ports: 
        - 10.0.0.8:9000:9000
    command: -e http://10.0.0.8:4000
    privileged: true

registry:
    image: registry:2
    restart: always
    ports:
        - 10.0.0.8:5000:5000 
